export const AUTH_DISCARD_TOKEN = 'AUTH_DISCARD_TOKEN';
export const API_REQUEST_SEND = 'API_REQUEST_SEND';

export const USER_REGISTER = "USER_REGISTER";
export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGOUT = "USER_LOGOUT";
export const UPDATE_USER_PROFILE = "UPDATE_USER_PROFILE";

export const CREATE_BOOK = "CREATE_BOOK";
export const GET_USER_BOOK_LIST = "GET_USER_BOOK_LIST";
export const GET_BOOK_DETAIL = "GET_BOOK_DETAIL";
export const UPDATE_BOOK_DETAIL = "UPDATE_BOOK_DETAIL";
export const DELETE_BOOK = "DELETE_BOOK";